### PR TITLE
Feature/typescript 2

### PR DESCRIPTION
**Pull request by mientjan**
This feature will move the boilerplate to typescript 2.0.3

### CODE REVIEW

**Comment by ThaNarie** [comment]
I was about to post that this update didn't include support for TypeDoc, as it doesn't support TS 2.0 yet. However, just found out that `0.5.0` does include initial TS 2.0 support.

The key here is **initial**, as it just includes the 2.0 compiler, and doesn't understands the new TS 2.0 features. It seems it can compile the codebase fine, however:
- no support yet for tsconfig fileglobs (includes, excludes), so `"src/**/*.ts"` trick doesn't work yet for generating docs. Need to decide what to do here... (wait for glob support, or revert the glob change in our config file and list all files manually, or create (another) tsconfig file just for docs)
- new features like 'readonly' are not marked like that in the docs

PR itself looks good btw :)

**Comment by flut1** [comment]
Why did you remove all typings from typings.json? Specifically `webpack-env`, it provides typings for the `require` function. Instead we now locally declare `require`:

```
// test/index.js
declare var require:any;
```

**Comment by ThaNarie** [comment]
IIRC there was an issue with the `webpack-env` typings package, that included (as a sub-dep) other typings that conflicted (I think because they were global types) with the normal typings we explicitly listed.

This seemed to work at first, using npm 2.x with a nested tree, but when we switched to npm 3.x we got a flat tree. And it seems that TS loads all the @types packages from the root of the tree automatically.

**Comment by flut1** [comment]
@ThaNarie @mientjan The latest Typedoc release now supports TS 2.2

**Comment by flut1** [comment]
#47

**Pull request merged**
